### ISSUE TITLE
Error when trying to enable the import-export ogre in blender 

### ISSUE THREAD

**Issue by ylldritt** [OGRECave/blender2ogre#175]
Would someone please help me with this issue, i keep getting this error message when i try to enbale the import-export:ogre addon in blender. 

This is the error message that i get. 

![Screenshot 2023-04-06 210642](https://user-images.githubusercontent.com/130100361/230483477-1b00067c-f638-4cff-8a55-f0c33eb5f0d3.png)

**Comment by sercero** [comment]
Bummer, supposedly this isse was resolved.

Let me take a look at it.

Might be a Blender 3.5 thing.

What Windows version are you using?

**Comment by ylldritt** [comment]
@sercero Hi there, i am currently running windows 11

**Comment by sercero** [comment]
As a quick fix you can comment this line:
`io_ogre/properties.py` (line 5):
```
#load_user_materials()
```

**Comment by ylldritt** [comment]
@sercero That seemed to fix it, and i was able to export an object however the same error keeps coming back when i close blender and open it again. 

Now nothing seems to fix it i re downloaded blender and the zip file for blender2ogre as well but still the same error.
 So it only worked once and now i get the same error. Because when i re open blender the export to ogre option is gone and when i go back to turn the add on same error appears.

It might have something to do with windows 11

**Comment by sercero** [comment]
Might be a thing with Windows 11, but there are also parts of the code that don't check for read permission before reading.

I was updating those functions, but wanted to give a quick fix before that.

Tomorrow I will push a better fix.

**Comment by ylldritt** [comment]
Okay thanks a lot i appreciate your help :)

**Comment by sercero** [comment]
I installed Windows 11, Blender 3.5.0 and created a local user without administrator privileges.

Even then, I was unable to replicate your scenario.

Anyway I did some modifications in the code that hopefully will resolve your situation but I'm unable to test them.

Can you check this branch to see if it works for your?
https://github.com/sercero/blender2ogre/tree/permissions

**Comment by ylldritt** [comment]
Okay i will give it a shot in a bit and will let u know, sorry just one more question, if this new repo doesn't work and i keep doing the step that u told me about before, dose that mean that my extracted meshes will have no textures, because thats what happened the first time when i extracted a mesh and i rendered it in ogre it had no texture. Thanks @sercero

**Comment by sercero** [comment]
No, I think that might be a different issue.
But perhaps the textures were not copied by ´blender2ogre´.
Could be many different things unfortunately.
It might be best if you ask in the OGRE forums for that one...

**Comment by ylldritt** [comment]
Just to let u know the new repo still didnt work for me, anyways thanks for you help and time i really appreciate it.

**Comment by sercero** [comment]
Are you still unable to enable the `blender2ogre` plugin or are you stuck in a later step?

**Comment by ylldritt** [comment]
Yea still stuck on the blender part where i try to enable the ogre add on. It only works when i add the # on line 5 like u told me, thats the only way i can get it to work. @sercero

**Comment by sercero** [comment]
I managed to replicate the problem.

Try my repo again.

**Comment by ylldritt** [comment]
unfortunately still dosent work,still the same error. I have the admin privilages enabled, do u think that can cause the issue? @sercero

**Comment by sercero** [comment]
Do you have a log?

The error should not be the same...

Also show me a screenshot of the Add-On menu with all the paths, I want to know where "User Materials" is pointing to.

Another thing: how did you install Blender?

Thanks!

**Comment by ylldritt** [comment]
On a side note, i had to take that screenshot when i added the # to the line 5 becasue if i do it with out doing that step the error appears and it wont let me click see the paths either. @sercero

**Comment by sercero** [comment]
The problem is that USER_MATERIALS is pointing towards "C:\\" where `blender2ogre` reads everything recursively and encounters a folder which it can't read.

Leave USER_MATERIALS variable empty.

What disturbs me is that with the latest changes I made to my repo you should not encounter that problem...

With the new changes you should see something like this:
```
[WARNING] Unable to parse 'USER_MATERIALS' directory: C:\
[WARNING] [WinError 5] Access is denied: 'C:\\$Recycle.Bin\\S-1-5-18'
```

**Comment by sercero** [comment]
The fix is in `master` branch
